config/routes.rb
Quickplace::Application.routes.draw do



  root to: 'home#home'
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  match '/users/auth/facebook' => 'devise/omniauth_callbacks#passthru',  via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create',   via: 'get'
  match 'auth/failure', to: redirect('/'),                  via: 'get'
  match '/users/sign_out',    to: 'devise/sessions#destroy',    via: 'post'
  match '/places',    to: 'quickplace#places',    via: 'get'
  match '/terms',    to: 'info#terms',    via: 'get'
  match '/merchantize',    to: 'info#promocionate',    via: 'get'
  match '/aboutus',   to: 'info#nosotros',   via: 'get'
  match '/contact', to: 'info#contacto', via: 'get'
  match '/micrositios', to: 'micrositios#index', via: 'get'




  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :eventos do
    member do
      get :following, :followers
    end
  end
  resources :micrositios do
    resources :actividades
    member do
      get :following, :followers
    end
  end

  resources :locations do
    resources :actividades

  end



  resources :users
  resources :actividades
  resources :micrositios
  resources :reservations
  resources :locations
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :relationeventos, only: [:create, :destroy]
  resources :relationmicrositios, only: [:create, :destroy]

end

app/models/micrositio.rb
class Micrositio < ActiveRecord::Base


  has_many :eventos, :primary_key => "uid"
  has_many :reservations
  has_many :reverse_relationmicrositios, foreign_key: "followed_id",
           class_name:  "Relationmicrositio",
           dependent:   :destroy
  has_many :followers, through: :reverse_relationmicrositios, source: :follower




  extend FriendlyId
  friendly_id :name, use: :slugged


end

app/controllers/micrositios_controller.rb
class MicrositiosController < ApplicationController
  before_action :correct_user,   only: :destroy
  before_action :set_micrositio, only: [:show, :edit, :update, :destroy]


  # GET /micrositios
  # GET /micrositios.json
  def index
    @micrositios = Micrositio.all
  end

  # GET /micrositios/1
  # GET /micrositios/1.json
  def show
    @micrositios = Micrositio.all
    @micrositio = Micrositio.friendly.find(params[:id])
  end

  # GET /micrositios/new
  def new
    @micrositio = Micrositio.new
  end

  # GET /micrositios/1/edit
  def edit
  end

  # POST /micrositios
  # POST /micrositios.json
  def create
    @micrositio = Micrositio.find_or_create_by(micrositio_params)
    respond_to do |format|
      if @micrositio.save
        format.html { redirect_to @micrositio, notice: '¡El Micrositio fue creado exitosamente!.' }
        format.json { render action: 'show', status: :created, location: @micrositio }
      else
        format.html { render action: 'new' }
        format.json { render json: @micrositio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /micrositios/1
  # PATCH/PUT /micrositios/1.json
  def update
    respond_to do |format|
      if @micrositio.update(micrositio_params)
        format.html { redirect_to @micrositio, notice: 'Micrositio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @micrositio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micrositios/1
  # DELETE /micrositios/1.json
  def destroy
    @micrositio.destroy
    respond_to do |format|
      format.html { redirect_to micrositios_url }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micrositio
      @micrositio = Micrositio.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def micrositio_params
    params.require(:micrositio).permit(:name,  :descripcion, :photo, :reference, :actividad_id, :lat, :lng, :referencefb, :photo_file_name)
  end



end

app/views/micrositios/_follow.html.erb
<%= form_for(current_user.relationmicrositios.build(followed_id: @micrositio.id), remote: true) do |f| %>
    <div><%= f.hidden_field :followed_id %></div>
    <%= f.submit "Seguir", class: "btn btn-large btn-primary" %>
<% end %>

app/views/micrositios/_follow_form.html.erb
    <div id="follow_form">
      <% if current_user.followingmicrositio?(@user) %>
          <%= render 'unfollow' %>
      <% else %>
          <%= render 'follow' %>
      <% end %>
    </div>

app/views/micrositios/_form.html.erb
<%= form_for(@micrositio) do |f| %>
  <% if @micrositio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micrositio.errors.count, "error") %> prohibited this micrositio from being saved:</h2>

      <ul>
      <% @micrositio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/micrositios/_lista_micrositios.html.erb
<div id="micrositiotitulo" >

<% @micrositionuevoleon.each do |micrositio| %>
    <li>
    <tr>

      <h1 class="micrositiotitulotexto"><%= micrositio.nombre%> </h1>
      <ul><%= micrositio.descripcion %> </ul>

    </tr>
    </li>
<% end %>

</div>

app/views/micrositios/_micrositio.html.erb
<li>
  <span class="content"><%= micrositio.name %></span>
  <span class="timestamp">
    Creado <%= time_ago_in_words(micrositio.created_at) %> ago.
  </span>
  <% if current_user?(micrositio.user) %>
    <%= link_to "delete", micrositio, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micrositio.name %>
  <% end %>
</li>

app/views/micrositios/_micrositios.html.erb
<li>
  <span class="content"><%= @micrositio %></span>
  <span class="timestamp">

  </span>

</li>

app/views/micrositios/_unfollow.html.erb
<%= form_for(current_user.relationmicrositios.find_by(followed_id: @micrositio), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "No seguir", class: "btn btn-large" %>
<% end %>

app/views/micrositios/edit.html.erb
<h1>Editing micrositio</h1>

<%= render 'form' %>

<%= link_to 'Show', @micrositio %> |
<%= link_to 'Back', micrositios_path %>

app/views/micrositios/fotos.html.erb
<div class="fotoscontainer">
<div class="fototitulo"></div>
  <h4>PRUEBA</h4>
<div class="fotogrande">
  <%=	 image_tag "sitios/big/002747722bff1704439aabc95adbdae5.jpg" %>
</div>

</div>

app/views/micrositios/index.html.erb
    <h1>Todos los lugares</h1>


    <% @micrositios.limit(20).order("RANDOM()").each do |estado| %>
        <ul class="thumbnail col-md-4 col-lg-3 col-sm-6 col-xs-12">

          <div style="height: 250px">
            <% if estado.photo_file_size? %>
                <%= image_tag estado.photo.url(:big), class: "img-responsive", alt: "responsive image", height: 250 %>
            <% else %>
                <img src="https://s3.amazonaws.com/imagenes.notelimites/micrositios/photos/sitios/big/<%= estado.photo_file_name %>" height="250px" width="100%" alt="Responsive image">
            <% end %>
          </div>
          <div class="caption">
            <h3><%= link_to estado.name.first(14), estado %> </h3>
            <div class="row" style="max-height: 60px; overflow: hidden">


            </div>
            <div class="row">
              <div class="col-md-12">
                <p>
                <div class="descripcionmicrositios">   <%=  estado.descripcion  %>  </div>
                </p>
              </div>
            </div>
            <div class="row " style="margin-bottom: 10px; font-weight: bold">
              <div class="col-md-8 col-md-offset-2">
                <%=	 link_to "Ver más -->", estado %>
              </div>
            </div>
            <div class="row" style="margin-top: 5px">
              <div class="col-md-6 col-sm-6 col-xs-6">
                <div id="follow_form" >
                  <% if current_user.followingestado?(estado) %>
                      <%= form_for(current_user.relationestados.find_by(followed_id: estado), html: { method: :delete }) do |f| %>
                          <%= f.submit "Siguiendo", class: "btn " %>
                      <% end %>
                  <% else %>
                      <%= form_for(current_user.relationestados.build(followed_id: estado.id)) do |f| %>
                          <div><%= f.hidden_field :followed_id %></div>
                          <%= f.submit "Seguir", class: "btn  btn-primary" %>
                      <% end %>
                  <% end %>
                </div>
              </div>
              <div class="col-md-4 col-sm-6 col-xs-6 estadocontador">
                <%= estado.followers.count%>
                lo siguen
              </div>

            </div>
          </div>
        </ul>
    <% end %>

app/views/micrositios/new.html.erb
<% if signed_in?   %>

    <script>
        var map, placesList;
        function initialize() {
            var pyrmont = new google.maps.LatLng(-33.8665433, 151.1956316);

            map = new google.maps.Map(document.getElementById('map-canvas'), {
                center: pyrmont,
                zoom: 17
            });
            var request = {
                location: pyrmont,
                radius: 500,
                types: ['restaurant']
            };
            placesList = document.getElementById('places');

            var service = new google.maps.places.PlacesService(map);
            service.nearbySearch(request, callback);
        }
        function callback(results, status, pagination) {
            if (status != google.maps.places.PlacesServiceStatus.OK) {
                return;
            } else {
                createMarkers(results);

                if (pagination.hasNextPage) {
                    var moreButton = document.getElementById('more');

                    moreButton.disabled = false;

                    google.maps.event.addDomListenerOnce(moreButton, 'click',
                            function() {
                                moreButton.disabled = true;
                                pagination.nextPage();
                            });
                }
            }
        }
        function createMarkers(places) {
            var bounds = new google.maps.LatLngBounds();
            for (var i = 0, place; place = places[i]; i++) {
                var image = {
                    url: place.icon,
                    size: new google.maps.Size(71, 71),
                    origin: new google.maps.Point(0, 0),
                    anchor: new google.maps.Point(17, 34),
                    scaledSize: new google.maps.Size(25, 25)
                };

                var marker = new google.maps.Marker({
                    map: map,
                    icon: image,
                    title: place.name,
                    position: place.geometry.location
                });

                placesList.innerHTML += '<li style="border: solid 1px #000000">' + place.reference + '</li>';

                bounds.extend(place.geometry.location);
            }
            map.fitBounds(bounds);
        }

        google.maps.event.addDomListener(window, 'load', initialize);

    </script>
    <h1>Nuevo micrositio</h1>
        <div id="map-canvas" style="height: 400px; width: 600px"></div>
        <div id="results" class="row">
          <h2>Results</h2>
          <ul id="places" style="margin: 5px"></ul>
          <button id="more">More results</button>
        </div>

        <%= form_for(@micrositio, :html => { :multipart => true }) do |f| %>

            <div id="results" class="row">
              <h2>Results</h2>

              <ul > <%= f.text_field :reference, class: 'input-sm', id: 'places' %></ul>

              <button id="more">More results</button>
            </div>


            <div class="col-md-4 col-md-offset-4" style="margin-bottom: 10px"><%= f.submit "Sube los lugares", class: 'btn btn-primary' %></div>
        <% end %>


<%	 else %>

<%	 end %>

app/views/micrositios/show.html.erb
<div class="hidden-xs" id="googlemaps">
  <div id="map-canvas"></div>
</div>

<div class="container" style="margin-top: 20px">



<%	 if signed_in? %>


    <%	event = ActiveSupport::JSON.decode(open("https://graph.facebook.com/#{@micrositio.uid}/events?fields=location,cover,name,description,picture,venue&access_token=#{current_user.oauth_token}").read) %>
    <% event['data'].each do |result| %>
        <% unless Evento.exists?(uid: result['id'])   %>
            <%	 if Rails.env.development? %>
                <%
                   conn = PG.connect(:dbname => 'ntlcom_dev')
                   conn.prepare('statement1', 'INSERT INTO eventos (uid, name,  description, lat, lng, imagen, city, slug, micrositio_id) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)')
                   conn.exec_prepared('statement1', [ result['id'], result['name'],result['description'],result['venue']['latitude'],result['venue']['longitude'],result['cover']['source'], result['location']['city'], result['name'].parameterize, result['venue']['id'] ])
                %>
            <%	 else %>
                <%
                   conn = PG::Connection.new(:dbname => 'd2roibus5os3io', :host => 'ec2-54-204-21-178.compute-1.amazonaws.com', :user => 'osdnvffmzogwhj', :password => 'uSCN8IqQulVTUP7j-ZVDxPYAjX', :port => '5432', :sslmode => 'disable')
                   conn.prepare('statement1', 'INSERT INTO eventos (uid, name,  description, lat, lng, imagen, city, slug, micrositio_id) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)')
                   conn.exec_prepared('statement1', [ result['id'], result['name'],result['description'],result['venue']['latitude'],result['venue']['longitude'],result['cover']['source'], result['location']['city'], result['name'].parameterize, result['venue']['id'] ])
                %>
            <%	 end %>
        <%	 end %>
    <%	end  %>


    <%	place = ActiveSupport::JSON.decode(open("https://graph.facebook.com/#{@micrositio.uid}?fields=picture.width(250),photos,likes,hours,name,posts,location,were_here_count,talking_about_count,description&access_token=#{current_user.oauth_token}").read) %>

    <div class="col-md-6 col-sm-6 col-xs-6 border" style="margin: 20px 0px 20px 0px" >
      <div class="row" style="margin-bottom: 10px; padding-top: 20px" >
        <div class="col-md-5 col-xs-12">
          <div class="img-responsive">
            <%	 if place['picture'].nil?  %>
            <%	else  %>
                <div class="img-responsive" style="height: 350px; overflow: hidden">
                  <%= image_tag(place['picture']['data']['url'])   %>
                </div>
            <%	end  %>
          </div>
        </div>
        <div class="col-md-7 col-xs-12">
          <h1> <%= place['name']	  %></h1>
          <h4> <%= place['location']['street']	  %></h4>
          <h4> <%= place['location']['city']	  %></h4>
          <h4> <%= place['location']['country']	  %></h4>
          <h5> <p style="font-weight: bold; font-size: 16px"> <%= place['were_here_count']  %>   persons where here.</p> </h5>
          <h5> <p style="font-weight: bold; font-size: 16px"> <%= place['talking_about_count']  %>   are talking about this place.</p> </h5>
          <h5> <p style="font-weight: bold; font-size: 16px"> <%= place['likes']  %>  likes in Facebook.</p> </h5>

        </div>
      </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 border" style="margin: 0px 0px 20px 0px" >
      <div class="row" style="margin-bottom: 10px; padding-top: 20px" >
        <div class="col-md-8 col-xs-12">

          <h2>Eventos</h2>
        </div>
            <% unless @micrositio.eventos.nil? %>
                <%	 @micrositio.eventos.last(2).each do |evento| %>
                <div class="col-md-6">
                      <div class="img-responsive" style="text-align: center;">
                        <%=link_to(image_tag(evento.imagen, style: "max-width: 100%"), evento) %>
                      </div>
                      <h5 style="margin-left: 30px; color: #3c598c"> Nombre: <%= link_to evento.name, evento	  %></h5>
                </div>
                <%	 end %>

            <%	end  %>

        <div class="col-md-7 col-xs-12">


        </div>
      </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 border" style="margin-bottom: 15px">
      <div class="row">
        <div class="col-md-8 col-xs-12">

          <h2>Description</h2>
          <p> <%= place['description']	  %></p>
        </div>
        <div class="col-md-4 col-xs-12">

          <%	 if place['hours'].nil?  %>
          <%	else  %>
              <h2>Hours</h2>
              <% place['hours'].each do |x|  %>
                  <%= x  %>
                  <br/>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 border" style="margin-bottom: 15px">
      <div class="row" style="margin-top: 20px">
        <div class="col-md-5 col-xs-12">
          <%	 if place['photos'].nil?  %>
          <%	else  %>
              <h2>Recently photos</h2>
              <br/>
              <% place['photos']['data'].first(4).each do |x|  %>
                  <div class="row">
                    <div class="img-responsive" style="overflow: hidden">
                      <%	 if x['source'].nil?  %>
                      <%	 else %>
                          <%= image_tag(x['source'], class: "micrositiophotos")  %>
                      <%	 end %>
                    </div>
                  </div>
              <%	 end %>
          <%	 end %>
        </div>
        <div class="col-md-7 col-xs-12">
          <%	 if place['posts'].nil?  %>
          <%	else  %>
              <h2>Posts</h2>
              <% place['posts']['data'].first(6).each do |x|  %>
                  <div class="row">
                    <div class="col-md-4 col-xs-4">
                      <div class="img-responsive" style="overflow: hidden; height: 100px">
                        <%= image_tag(x['picture'], class: "micrositiopostphotos")  %>
                      </div>
                    </div>
                    <div class="col-md-8 col-xs-8">
                      <%= x['message']  %>
                    </div>
                  </div>
                  <hr/>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 border" >
      <div class="fb-comments" data-href="<%=request.original_url%>" data-numposts="10" data-width= "280"></div>
    </div>
<% else %>


      <div class="col-md-7 col-sm-7 col-xs-7 border" style="margin: 20px 0px 20px 0px" >
        <div class="row" style="margin-bottom: 10px; padding-top: 20px" >
          <div class="col-md-5 col-xs-12">
            <div class="img-responsive">
              <%	 if @micrositio.imagen.nil?  %>
              <%	else  %>
                  <div class="img-responsive" style="height: 350px; overflow: hidden">
                    <%= image_tag(@micrositio.imagen)   %>
                  </div>
              <%	end  %>
            </div>
          </div>
          <div class="col-md-7 col-xs-12">
            <h1> <%= @micrositio.name	  %></h1>
            <h4> <%= @micrositio.city  %></h4>
            <h5> <p style="font-weight: bold; font-size: 16px"> -----  persons where here.</p> </h5>
            <h5> <p style="font-weight: bold; font-size: 16px"> -----   are talking about this place.</p> </h5>
            <h5> <p style="font-weight: bold; font-size: 16px"> ----- likes in Facebook.</p> </h5>

          </div>
        </div>
      </div>
      <div class="col-md-12 col-sm-12 col-xs-12 border" style="margin-bottom: 15px">
        <div class="row">
          <div class="col-md-8 col-xs-12">

            <h2>Description</h2>
            <p> <%= @micrositio.description	  %></p>
          </div>
          <div class="col-md-4 col-xs-12">


          </div>
        </div>
      </div>
      <div class="col-md-12 col-sm-12 col-xs-12 border" style="margin-bottom: 15px">
        <div class="row" style="margin-top: 20px">
          <div class="col-md-5 col-xs-12">
            <%	 if @micrositio.imagen.nil?  %>
            <%	else  %>
                <h2>Recently photos</h2>
                <br/>

            <%	 end %>
          </div>
          <div class="col-md-7 col-xs-12">

          </div>
        </div>
      </div>
      <div class="col-md-12 col-sm-12 col-xs-12 border" >
        <div class="fb-comments" data-href="<%=request.original_url%>" data-numposts="10" data-width= "280"></div>
      </div>


<% end %>



  <script>
      $(document).ready(function () {
          var myLatlng = new google.maps.LatLng(<%= @micrositio.lat  %>,<%= @micrositio.lng %>);
          var centerlat = new google.maps.LatLng(<%= @micrositio.lat.to_d - 0.02  %>,<%=   @micrositio.lng.to_d - 0.05 %>);
          var mapOptions = {
              zoom: 13,
              center: centerlat,
              scrollwheel: false,
              navigationControl: false,
              mapTypeControl: false,
              scaleControl: false,
              mapTypeControl: false,
              panControl: false,
              rotateControl: false,
              scaleControl: false,
              streetViewControl: false,
              zoomControl: false,
              tilt: 45
          }
          var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

          <% i = 0 %>
          var locations = [
              ['<%= @micrositio.name %>', <%= @micrositio.lat  %>,<%= @micrositio.lng %>, <%= i = i + 1 %>],
          ];
          var infowindow = new google.maps.InfoWindow();
          var marker, i;
          for (i = 0; i < locations.length; i++) {
              marker = new google.maps.Marker({
                  position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                  map: map
              });

              google.maps.event.addListener(marker, 'mouseover', (function(marker, i) {
                  return function() {
                      infowindow.setContent(locations[i][0]);
                      infowindow.open(map, marker);
                  }
              })(marker, i));

              google.maps.event.addListener(marker, 'mouseout', (function(marker, i) {
                  return function() {
                      infowindow.close();
                  }
              })(marker, i));
          }
      });
  </script>

</div>