config/routes.rb
Quickplace::Application.routes.draw do



  root to: 'home#home'
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  match '/users/auth/facebook' => 'devise/omniauth_callbacks#passthru',  via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create',   via: 'get'
  match 'auth/failure', to: redirect('/'),                  via: 'get'
  match '/users/sign_out',    to: 'devise/sessions#destroy',    via: 'post'
  match '/places',    to: 'quickplace#places',    via: 'get'
  match '/terms',    to: 'info#terms',    via: 'get'
  match '/merchantize',    to: 'info#promocionate',    via: 'get'
  match '/aboutus',   to: 'info#nosotros',   via: 'get'
  match '/contact', to: 'info#contacto', via: 'get'
  match '/micrositios', to: 'micrositios#index', via: 'get'




  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :eventos do
    member do
      get :following, :followers
    end
  end
  resources :micrositios do
    resources :actividades
    member do
      get :following, :followers
    end
  end

  resources :locations do
    resources :actividades

  end



  resources :users
  resources :actividades
  resources :micrositios
  resources :reservations
  resources :locations
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :relationeventos, only: [:create, :destroy]
  resources :relationmicrositios, only: [:create, :destroy]

end

app/views/shared/_actividadespadre.html.erb
<ul >


  <% @actividadpadres.each do |actividad| %>



      <li>
       <div class="actividadespadretitulo"> <%= link_to actividad.descripcion, actividad %> </div>
        <div class="actividadespadrefollow">
          <div class="actividadespadrebarrafollow">
              <div class="actividadespadrefollow">
                  <div id="follow_form" >
                    <% if current_user.followingactividadpadre?(actividad) %>
                        <%= form_for(current_user.relationactividadespadre.find_by(followed_id: actividad), html: { method: :delete }) do |f| %>
                            <%= f.submit "Siguiendo", class: "btn " %>
                        <% end %>
                    <% else %>
                        <%= form_for(current_user.relationactividadespadre.build(followed_id: actividad.id)) do |f| %>
                            <div><%= f.hidden_field :followed_id %></div>
                            <%= f.submit "Seguir", class: "btn  btn-primary" %>
                        <% end %>
                    <% end %>
                  </div>
              </div>
              <div class="actividadespadrecontador">
                <%= actividad.followers.count%>
                Usuarios

              </div>
          </div>

        </div>
      </li>


  <% end %>


</ul>

app/views/shared/_avatar.html.erb
<% if current_user.photo_file_name.blank?  %>
    <% if current_user.avatar.blank?  %>
        <%= link_to image_tag("http://imagenes.notelimites.s3.amazonaws.com/users/default_user.png", class: "avatarchico"), current_user %>
    <%	 else %>
        <%= link_to image_tag("http://graph.facebook.com/#{current_user.uid}/picture?type=square", class: "avatarchico"), current_user %>
    <% end %>
<% else %>
    <%= link_to image_tag(current_user.photo.url(:square), class: "avatarchico"), current_user  %>
<%	 end %>

app/views/shared/_estados.html.erb
<ul >
  <% @estadosalf.each do |estado| %>
      <li class="estados">
       <div class="estadostitulo"> <%= link_to estado.estado, estado %> </div>
        <%= link_to image_tag(estado.photo.url(:medium)), estado, class: 'estadoimagen'%>
        <div class="estadoarticulo"><%=  estado.descripcion %> </div>
        <div class="estadofollow">

          <div class="estadobarrafollow">
              <div class="estadofollow">
                  <div id="follow_form" >
                    <% if current_user.followingestado?(estado) %>
                        <%= form_for(current_user.relationestados.find_by(followed_id: estado), html: { method: :delete }) do |f| %>
                            <%= f.submit "Siguiendo", class: "btn " %>
                        <% end %>
                    <% else %>
                        <%= form_for(current_user.relationestados.build(followed_id: estado.id)) do |f| %>
                            <div><%= f.hidden_field :followed_id %></div>
                            <%= f.submit "Seguir", class: "btn  btn-primary" %>
                        <% end %>
                    <% end %>
                  </div>
              </div>
              <div class="estadocontador">
                <%= estado.followers.count%>
                Usuarios
              </div>
          </div>
        </div>
      </li>
  <% end %>


</ul>

app/views/shared/_estadosfollow.html.erb
<ul >
  <% @estadosalf.each do |estado| %>



      <li class="estados">
       <div class="estadostitulo"> <%= link_to estado.estado, estado %> </div>
        <%= link_to image_tag(estado.photo.url(:medium)), estado, class: 'estadoimagen'%>
        <div class="estadoarticulo"><%=  estado.descripcion %> </div>
        <div class="estadofollow">


          <div id="follow_form">
            <% if current_user.followingestado?(estado) %>
                <%= form_for(current_user.relationestados.find_by(followed_id: estado), html: { method: :delete }) do |f| %>
                    <%= f.submit "Unfollow", class: "btn " %>
                <% end %>
            <% else %>
                <%= form_for(current_user.relationestados.build(followed_id: estado.id)) do |f| %>
                    <div><%= f.hidden_field :followed_id %></div>
                    <%= f.submit "Seguir", class: "btn  btn-primary" %>
                <% end %>
            <% end %>
          </div>


        </div>
      </li>


  <% end %>
</ul>

app/views/shared/_eventos.html.erb
<ul >
  <% @eventos.take(10).each do |estado| %>

      <div class="thumbnail seleccionado" style="margin: 0px">
        <div >
          <% if estado.photo_file_size? %>
              <%= image_tag estado.photo.url(:big), class: "img-responsive", alt: "responsive image" %>
          <% else %>
              <img src="https://s3.amazonaws.com/imagenes.notelimites/micrositios/photos/sitios/big/<%= estado.photo_file_name %>" class="img-responsive" alt="Responsive image">
          <% end %>
        </div>
        <div class="caption">
          <h3><%= link_to estado.nombre, estado %> </h3>
          <div class="row">
            <div class="col-md-3">
              <% if estado.user.photo_file_name.blank?  %>
                  <% if estado.user.avatar.blank?  %>
                      <%= link_to image_tag("http://imagenes.notelimites.s3.amazonaws.com/users/default_user.png", class: "avatarchico"), estado.user %>
                  <%	 else %>
                      <%= link_to image_tag(estado.user.avatar, class: "avatarchico" ), estado.user %>
                  <% end %>
              <% else %>
                  <%= link_to image_tag(estado.user.photo.url(:square), class: "avatarchico"), estado.user %>
              <%	 end %>
            </div>
            <div class="col-md-9">
              <%= link_to estado.user.name , estado %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <p>
              <div class="descripcionmicrositios">   <%=  estado.descripcion  %>  </div>
              </p>
            </div>
          </div>
          <div class="row " style="margin-bottom: 10px; font-weight: bold">
            <div class="col-md-6 col-md-offset-6">
              <%=	 link_to "Ver más -->", estado %>
            </div>
          </div>
          <div class="row" style="margin-top: 5px">
            <div class="col-md-6">
              <div id="follow_form" >
                <% if current_user.followingestado?(estado) %>
                    <%= form_for(current_user.relationestados.find_by(followed_id: estado), html: { method: :delete }) do |f| %>
                        <%= f.submit "Siguiendo", class: "btn " %>
                    <% end %>
                <% else %>
                    <%= form_for(current_user.relationestados.build(followed_id: estado.id)) do |f| %>
                        <div><%= f.hidden_field :followed_id %></div>
                        <%= f.submit "Seguir", class: "btn  btn-primary" %>
                    <% end %>
                <% end %>
              </div>
            </div>
            <div class="col-md-4 estadocontador">
              <%= estado.followers.count%>
              Usuarios lo siguen
            </div>

          </div>
        </div>
      </div>

  <% end %>

</ul>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
      <%= render partial: 'shared/feed_item', collection: @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <div class="row">
    <div class="col-md-2">
      <% if feed_item.user.photo_file_name.blank?  %>
          <% if feed_item.user.avatar.blank?  %>
              <%= link_to image_tag("http://imagenes.notelimites.s3.amazonaws.com/users/default_user.png", class: "avatarchico", :size => "100x50" ), feed_item.user %>
          <%	 else %>
              <%= link_to image_tag(feed_item.user.avatar, class: "avatarchico", :size => "100x50" ), feed_item.user %>
          <% end %>
      <% else %>
          <%= link_to image_tag(feed_item.user.photo.url(:square), class: "avatarchico", :size => "100x50" ), feed_item.user %>
      <%	 end %>


    </div>
    <div class="col-md-6">
      <div class="row">
        <%= link_to feed_item.user.name, feed_item.user %>
      </div>
      <div class="row">
        Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
      </div>
    </div>
    <div class="col-md-4">
      <span class="content"><%= feed_item.content %></span>
    </div>
  </div>
</li>

app/views/shared/_googlepin.html.erb
<script type="text/javascript">
    function initialize() {

        var myLatlng = new google.maps.LatLng(23.634501,-102.55278399999997);
        var mapOptions = {
            zoom: 4,
            center: myLatlng,
        }
        var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

        // Place a draggable marker on the map
        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            draggable:true,
            title:"Your location!"
        });

        google.maps.event.addListener(marker, 'dragend', function (event) {
            document.getElementById("latbox").value = this.getPosition().lat();
            document.getElementById("lngbox").value = this.getPosition().lng();
        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/shared/_lugares.html.erb
<ul >
  <% @micrositios.each do |actividad| %>

      <li class="actividades">
       <div class="actividadestitulo"> <%= link_to actividad.name, actividad %> </div>
        <%= link_to image_tag(actividad.photo.url(:medium)), actividad, class: 'actividadesimagen'%>
        <div class="actividadesarticulo"><%=  actividad.descripcion %> </div>
        <div class="actividadesfollow">
          <div class="actividadesbarrafollow">
              <div class="actividadesfollow">
                  <div id="follow_form" >
                    <% if current_user.followingmicrositio?(actividad) %>
                        <%= form_for(current_user.relationmicrositios.find_by(followed_id: actividad), html: { method: :delete }) do |f| %>
                            <%= f.submit "Siguiendo", class: "btn " %>
                        <% end %>
                    <% else %>
                        <%= form_for(current_user.relationmicrositios.build(followed_id: actividad.id)) do |f| %>
                            <div><%= f.hidden_field :followed_id %></div>
                            <%= f.submit "Seguir", class: "btn  btn-primary" %>
                        <% end %>
                    <% end %>
                  </div>
              </div>
              <div class="actividadescontador">
                <%= actividad.followers.count%>
                Usuarios

              </div>
          </div>

        </div>
      </li>


  <% end %>


</ul>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Escribe tu mapost" %>
  </div>
  <%= f.submit "MaPost", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_micrositios.html.erb
  <% @micrositios.limit(20).order("RANDOM()").each do |x| %>



              <%  x.followers.limit(10).order("RANDOM()").each do |y|  %>
              <div class="thumbnail">
                <div class="caption">

                  <div>
                    <% if y.photo_file_name.blank?  %>
                        <% if y.avatar.blank?  %>
                            <%= link_to image_tag("http://imagenes.notelimites.s3.amazonaws.com/users/default_user.png", class: "avatarchico"), y %>
                        <%	 else %>
                            <%= link_to image_tag(y.avatar, class: "avatarchico" ), y %>
                        <% end %>
                    <% else %>
                        <%= link_to image_tag(y.photo.url(:square), class: "avatarchico"), y %>
                    <%	 end %>
                  </div>
                  <h4><%= y.name %></h4>
                  <p>ahora está siguiendo a <%= x.name %>  </p>
                      <% if x.photo_file_size? %>
                          <%= link_to (image_tag x.photo.url(:small), class: "img-responsive"), x %>
                          <div style="font-weight: bold; overflow: hidden"><%= link_to x.name, x		  %> </div>
                      <% else %>
                          <%= link_to (image_tag "https://s3.amazonaws.com/imagenes.notelimites/micrositios/photos/sitios/big/#{x.photo_file_name}", class: "img-responsive"),x %>
                          <div style="font-weight: bold; overflow: hidden"><%= link_to x.name, x		  %> </div>
                      <% end %>

                  <h3><%= x.name %></h3>
                  <p>...</p>
                </div>
              </div>

              <% end %>



  <% end %>



  <% @micrositios.limit(5).order("RANDOM()").each do |x| %>

  <div class="thumbnail">
    <div class="caption">
      <div>
        <% if x.user.photo_file_name.blank?  %>
            <% if x.user.avatar.blank?  %>
                <%= link_to image_tag("http://imagenes.notelimites.s3.amazonaws.com/users/default_user.png", class: "avatarchico"), x.user %>
            <%         else %>
                <%= link_to image_tag(x.user.avatar, class: "avatarchico"), x.user %>
            <% end %>
        <% else %>
            <%= link_to image_tag(x.user.photo.url(:square), class: "avatarchico"), x.user  %>
        <%         end %>
      </div>
      <h4><%= x.user.name %></h4>
      <p>creó el lugar</p>

      <% if x.photo_file_size? %>
          <%= link_to (image_tag @micrositio.photo.url(:biggest), class: "img-responsive"),x  %>
      <% else %>
          <%= link_to (image_tag "https://s3.amazonaws.com/imagenes.notelimites/micrositios/photos/sitios/big/#{x.photo_file_name}", class:"img-responsive"),x %>
      <% end %>
      <h3><%= x.name %></h3>

    </div>
  </div>

  <% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<p>--------------</p>
<p>USUARIOS</p>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    Siguiendo
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Te siguen
  </a>
</div>
<p>--------------</p>
<p>EVENTOS</p>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    Eventos Seguidos
  </a>
</div>

<p>--------------</p>
<p>LUGARES</p>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    Micrositios Seguidos
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">

  <% if @current_user.photo_file_name.blank?  %>
    <%= image_tag @current_user.avatar %>
  <%	 else %>
      <%= image_tag @user.photo.url(:square) %>
  <%	 end %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>-------</span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>
<span><%= pluralize(current_user.micrositios.count, "micrositio") %></span>
<span><%= pluralize(current_user.eventos.count, "eventos") %></span>

app/views/shared/_usuarios.html.erb
<% @users.limit(10).order("RANDOM()").each do |x| %>
    <div class="thumbnail">
      <div class="caption">

        <div>
          <% if x.photo_file_name.blank?  %>
              <% if x.avatar.blank?  %>
                  <%= link_to image_tag("http://imagenes.notelimites.s3.amazonaws.com/users/default_user.png", class: "avatarmedio"), x %>
              <%	 else %>
                  <%= link_to image_tag(x.avatar, class: "avatarmedio" ), x%>
              <% end %>
          <% else %>
              <%= link_to image_tag(x.photo.url(:medium), class: "avatarmedio"), x %>
          <%	 end %>
        </div>
        <h4><%= x.name %></h4>
        <p>es nuevo usuario  </p>


      </div>
    </div>
<% end %>