config/routes.rb
Quickplace::Application.routes.draw do



  root to: 'home#home'
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  match '/users/auth/facebook' => 'devise/omniauth_callbacks#passthru',  via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create',   via: 'get'
  match 'auth/failure', to: redirect('/'),                  via: 'get'
  match '/users/sign_out',    to: 'devise/sessions#destroy',    via: 'post'
  match '/places',    to: 'quickplace#places',    via: 'get'
  match '/terms',    to: 'info#terms',    via: 'get'
  match '/merchantize',    to: 'info#promocionate',    via: 'get'
  match '/aboutus',   to: 'info#nosotros',   via: 'get'
  match '/contact', to: 'info#contacto', via: 'get'
  match '/micrositios', to: 'micrositios#index', via: 'get'




  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :eventos do
    member do
      get :following, :followers
    end
  end
  resources :micrositios do
    resources :actividades
    member do
      get :following, :followers
    end
  end

  resources :locations do
    resources :actividades

  end



  resources :users
  resources :actividades
  resources :micrositios
  resources :reservations
  resources :locations
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :relationeventos, only: [:create, :destroy]
  resources :relationmicrositios, only: [:create, :destroy]

end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :user



  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :admin_user,     only: :destroy
  before_action :set_evento, only: [:show, :edit, :update, :destroy]


  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
    @evento = Evento.new

  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
    @eventos = Evento.all
    @micrositioevento= Micrositio.all
    @user = Evento.friendly.find(params[:id])
    @evento = Evento.friendly.find(params[:id])
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = current_user.eventos.find_or_create_by(evento_params)
    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento}
        format.json { render action: 'show', status: :created, location: @evento }
      else
        format.html { render action: 'new' }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url }
      format.json { head :no_content }
    end
  end



  private

  # Use callbacks to share common setup or constraints between actions.
  def set_evento
    @evento = Evento.friendly.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params[:evento].permit(:name, :descripcion, :photo, :precio, :fecha, :artista, :urloficial, :estado, :referencefb, :photo_file_name)
    end




end

app/views/eventos/_evento.html.erb
<li>
  <span class="content"><%= evento.nombre %></span>
  <span class="timestamp">
    Creado <%= time_ago_in_words(evento.created_at) %> ago.
  </span>
  <% if current_user?(evento.user) %>
    <%= link_to "delete", evento, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: evento.nombre %>
  <% end %>
</li>

app/views/eventos/_follow.html.erb
<%= form_for(current_user.relationeventos.build(followed_id: @evento.id), remote: true) do |f| %>
    <div><%= f.hidden_field :followed_id %></div>
    <%= f.submit "Add to Favorites", class: "btn btn-large btn-primary" %>
<% end %>

app/views/eventos/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
      <% if current_user.followingevento?(@user) %>
          <%= render 'unfollow' %>
      <% else %>
          <%= render 'follow' %>
      <% end %>
    </div>
<% end %>

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventos/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/eventos/_unfollow.html.erb
<%= form_for(current_user.relationeventos.find_by(followed_id: @evento), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "No seguir", class: "btn btn-large" %>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<%	 if signed_in? %>
    <div class="col-md-12 col-sm-12 col-xs-12" style="margin-bottom: 20px">
      <div class="row" style="background-color: #593e73; border-radius: 5px; padding: 15px;  margin-top: -10px; ">
        <div class="col-md-6 col-sm-6 hidden-xs">
          <h1 style="color: #ffffff">Events </h1>
        </div>
        <div class="visible-xs col-xs-6">
        </div>
      </div>
    </div>
    <%	fbevents = ActiveSupport::JSON.decode(open("https://graph.facebook.com/search?q=summer&type=event&fields=cover,name,location&center=#{current_user.lat},#{current_user.lng}&distance=50000&access_token=#{current_user.oauth_token}&limit=20").read) %>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" style="border: 1px solid #d3d6db; " >
      <% fbevents['data'].each do |result| %>

          <div class="row" style="margin-bottom: -15px;  margin-top: -10px">
            <div class="col-md-3 col-sm-3 col-xs-4">
              <%	 if result['cover'].nil?  %>
              <%	else  %>
                  <div class="img-responsive" style="height: 110px; overflow: hidden">
                    <%=  image_tag(result['cover']['source']) %>
                  </div>
              <%	end  %>
            </div>
            <div class="col-md-7 col-sm-7 col-xs-8" style="padding: 0 !important;">
              <div class="col-md-3 col-sm-6 col-xs-12 hidden-xs" style="padding: 0 !important; text-align: center ">
                <%= form_for(@evento) do |f| %>
                    <%= f.hidden_field :name, value: result['name'] %>
                    <%= f.hidden_field :referencefb, value: result['id'] %>
                    <%	 if result['cover'].nil?  %>
                    <%	else  %>
                        <%= f.hidden_field :photo_file_name, value: result['cover']['source'] %>
                    <% end %>
                    <%= f.submit result['name'], class: "btn-success" %>
                <% end %>
              </div>
              <div class="col-md-5 col-sm-3 hidden-xs" style="padding: 0 !important; text-align: center">
                <h6>Attending</h6>
              </div>
              <div class="col-md-4 col-sm-3 hidden-xs" style="padding: 0 !important; text-align: center">
                <h6>Friends that have been here</h6>
              </div>
              <div class="col-xs-12 visible-xs" style="padding:0 !important; margin-top: -10px; ">
                <div style="margin-top: 10px; margin-bottom: -15px">
                  <%= form_for(@evento) do |f| %>
                      <%= f.hidden_field :name, value: result['name'] %>
                      <%= f.hidden_field :referencefb, value: result['id'] %>
                      <%	 if result['cover'].nil?  %>
                      <%	else  %>
                          <%= f.hidden_field :photo_file_name, value: result['cover']['source'] %>
                      <% end %>
                      <%= f.submit result['name'], class: "btn-success" %>
                  <% end %>
                </div>
                <%	 if result['location'].nil?  %>
                <%	else  %>
                    <h6 style="font-size: 10px"><%= result['location']%></h6>
                <% end %>
                <h6 style="font-size: 10px">Friends attending </h6>

              </div>
            </div>
            <div class="col-md-2 col-sm-2 hidden-xs  ">
              <h6> Distance</h6>

            </div>
          </div>
          <hr/>

      <%	 end %>

    </div>

<% else %>
    <%=	 render "shared/ingresa" %>
<% end %>

app/views/eventos/new.html.erb
<script>
    $(document).ready(function(){


        $('#project_status').change(function(){
            if($(this).val() != "In Progress"){
                $("#project_capital_cost").attr('disabled','disabled');
            }
            else{
                $("#project_capital_cost").removeAttr('disabled');
            }
        })
    });

</script>


<% if signed_in?   %>
    <% if current_user.editor? or current_user.admin?  %>


    <h1>Nuevo Evento</h1>

      <div class="row">
        Como
      </div>

      <div class="row">
         Cada nuevo evento debe de estar ligado con un micrositio. Porfavor selecciona el micrositio donde será el evento. Si no existe ayudanos creándolo.
      </div>


    <div class="row">
      <div id="formrow">

        <%= form_for(@evento, :html => { :multipart => true }) do |f| %>

            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :estado_id %><br />
            <%= f.collection_select :estado_id, Estado.order(:estado), :id, :estado, id: "estadoselect"  %>


            <%= f.label :nombre %>
            <%= f.text_field :nombre %>

            <%= f.label :descripcion %>
            <%= f.text_area :descripcion %>

            <%= f.label :imagen %>
            <%= f.file_field :photo %>


            <%= f.label :artista %>
            <%= f.text_field :artista %>

            <%= f.label :precio %>
            <%= f.text_field :precio %>

            <%= f.label :"Página Web Oficial" %>
            <%= f.text_field :urloficial %>




            <%= f.label :fecha %>
            <%= f.date_select :fecha %>

            <%= f.submit "Sube tu evento", class: "btn btn-large btn-primary" %>

        <% end %>


      </div>
    </div>

    <%	 else %>

       <h2>Necesitas permisos para poder crear eventos</h2>
        <%=	 link_to "o puedes ver como promocionarte aquí", promocionate_path %>
    <%	 end %>
<%	 else %>
    <%=	 render "shared/ingresa" %>

<%	 end %>

app/views/eventos/show.html.erb
<%	 if signed_in? %>
    <%	place = ActiveSupport::JSON.decode(open("https://graph.facebook.com/#{@evento.referencefb}?fields=cover,name,location,description,start_time,end_time,parent_group,invited,posts&access_token=#{current_user.oauth_token}").read) %>
    <div class="col-md-12 col-sm-12 col-xs-12 border" style="margin-bottom: 15px" >
      <div class="row" style="margin-bottom: 10px; padding-top: 20px" >
        <div class="col-md-5 col-xs-12">
          <div class="img-responsive">
            <%	 if place['cover'].nil?  %>
            <%	else  %>
                <div class="img-responsive" style="height: 350px; overflow: hidden">
                  <%= image_tag(place['cover']['source'])   %>
                </div>
            <%	end  %>
          </div>
        </div>
        <div class="col-md-7 col-xs-12">

          <h1> <%= place['name']	  %></h1>

          <h5> <p style="font-weight: bold; font-size: 16px"> <%= place['were_here_count']  %>   persons where here.</p> </h5>
          <h5> <p style="font-weight: bold; font-size: 16px"> <%= place['talking_about_count']  %>   are talking about this place.</p> </h5>
          <h5> <p style="font-weight: bold; font-size: 16px"> <%= place['likes']  %>  likes in Facebook.</p> </h5>
          <div class="col-md-6" style="padding-top: 40px">
            <%= render 'follow_form' if signed_in? %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 border" style="margin-bottom: 15px">
      <div class="row">
        <div class="col-md-8 col-xs-12">

          <h2>Description</h2>
          <p> <%= place['description']	  %></p>
        </div>
        <div class="col-md-4 col-xs-12">


              <h2>Hours</h2>
              <% place['start_time']  %>

        </div>
      </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 border" style="margin-bottom: 15px">
      <div class="row" style="margin-top: 20px">
        <div class="col-md-4 col-xs-12">
          <%	 if place['photos'].nil?  %>
          <%	else  %>
              <h2>Recently photos</h2>
              <% place['photos']['data'].first(4).each do |x|  %>
                  <ul >
                    <li>
                      <div class="img-responsive" style="overflow: hidden">
                        <%= image_tag(x['source'])  %>
                      </div>
                      <%= x['from']['name']  %>
                    </li>
                  </ul>
              <%	end  %>
          <%	end  %>
        </div>
        <div class="col-md-8 col-xs-12">
          <%	 if place['posts'].nil?  %>
          <%	else  %>
              <h2>Posts</h2>
              <% place['posts']['data'].first(6).each do |x|  %>
                  <div class="row">
                    <div class="col-md-4 col-xs-4">
                      <div class="img-responsive" style="overflow: hidden; height: 100px">
                        <%= image_tag(x['picture'])  %>
                      </div>
                    </div>
                    <div class="col-md-8 col-xs-8">
                      <%= x['message']  %>
                    </div>
                  </div>
                  <hr/>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 border" >
      <div class="fb-comments" data-href="<%=request.original_url%>" data-numposts="10" data-width= "280"></div>
    </div>


<% else %>
    <%=	 render "shared/ingresa" %>
<% end %>

app/views/eventos/show_follow.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>

        <%= @evento.name %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <%= render 'follow_form' if signed_in? %>
    .
    .
    .
  </div>
</div>