config/routes.rb
Quickplace::Application.routes.draw do



  root to: 'home#home'
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  match '/users/auth/facebook' => 'devise/omniauth_callbacks#passthru',  via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create',   via: 'get'
  match 'auth/failure', to: redirect('/'),                  via: 'get'
  match '/users/sign_out',    to: 'devise/sessions#destroy',    via: 'post'
  match '/places',    to: 'quickplace#places',    via: 'get'
  match '/terms',    to: 'info#terms',    via: 'get'
  match '/merchantize',    to: 'info#promocionate',    via: 'get'
  match '/aboutus',   to: 'info#nosotros',   via: 'get'
  match '/contact', to: 'info#contacto', via: 'get'
  match '/micrositios', to: 'micrositios#index', via: 'get'




  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :eventos do
    member do
      get :following, :followers
    end
  end
  resources :micrositios do
    resources :actividades
    member do
      get :following, :followers
    end
  end

  resources :locations do
    resources :actividades

  end



  resources :users
  resources :actividades
  resources :micrositios
  resources :reservations
  resources :locations
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :relationeventos, only: [:create, :destroy]
  resources :relationmicrositios, only: [:create, :destroy]

end

app/controllers/actividades_controller.rb
class ActividadesController < ApplicationController
  before_action :set_actividad, only: [:show, :edit, :update, :destroy]

  # GET /actividades
  # GET /actividades.json
  def index
    @actividades = Actividad.all

  end

  # GET /actividades/1
  # GET /actividades/1.json
  def show
    @actividad = Actividad.find(params[:id])
    @actividades = Actividad.all

  end

  # GET /actividades/new
  def new
    @actividad = Actividad.new
  end

  # GET /actividades/1/edit
  def edit
  end

  # POST /actividades
  # POST /actividades.json
  def create
    @actividad = Actividad.new(actividad_params)
    respond_to do |format|
      if @actividad.save
        format.html { redirect_to @actividad, notice: 'Actividad was successfully created.' }
        format.json { render action: 'show', status: :created, location: @actividad }
      else
        format.html { render action: 'new' }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actividades/1
  # PATCH/PUT /actividades/1.json
  def update
    respond_to do |format|
      if @actividad.update(actividad_params)
        format.html { redirect_to @actividad, notice: 'Actividad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actividades/1
  # DELETE /actividades/1.json
  def destroy
    @actividad.destroy
    respond_to do |format|
      format.html { redirect_to actividades_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_actividad
    @actividad = Actividad.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def actividad_params
    params.require(:actividad).permit(:name)
  end
end

app/helpers/actividades_helper.rb
module ActividadesHelper


end

app/views/actividades/_follow.html.erb
<%= form_for(current_user.relationactividades.build(followed_id: @actividad.id), remote: true) do |f| %>
    <div><%= f.hidden_field :followed_id %></div>
    <%= f.submit "Seguir", class: "btn btn-large btn-primary" %>
<% end %>

app/views/actividades/_follow_form.html.erb
    <div id="follow_form">
      <% if current_user.followingactividad?(@actividad) %>
          <%= render 'unfollow' %>
      <% else %>
          <%= render 'follow' %>
      <% end %>
    </div>

app/views/actividades/_form.html.erb
<%= form_for(@actividad) do |f| %>
  <% if @actividad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actividad.errors.count, "error") %> prohibited this actividad from being saved:</h2>

      <ul>
      <% @actividad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actividades/_unfollow.html.erb
<%= form_for(current_user.relationactividades.find_by(followed_id: @actividad), html: { method: :delete }, remote: true) do |f| %>
    <%= f.submit "No seguir", class: "btn btn-large" %>
<% end %>

app/views/actividades/edit.html.erb
<div class="container" style="margin-top: 100px">
<div class="row">

    <%= form_for @actividad do |f| %>
        <%= render 'shared/error_messages', object: f.object %>


        <%= f.label :name %>
        <%= f.text_field :name %>


        <%= f.submit "Sube tu actividad", class: "btn btn-large btn-primary" %>

    <% end %>
</div>
</div>

app/views/actividades/new.html.erb
<div class="container">

<h1>New actividad</h1>


<%= form_for @actividad do |f| %>

    <%= render 'shared/error_messages', object: f.object %>


    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :namefb %>
    <%= f.text_field :namefb %>

    <%= f.label :namegoogle %>
    <%= f.text_field :namegoogle %>




    <%= f.submit "Sube tu actividad", class: "btn btn-large btn-primary" %>

<% end %>

<%= link_to 'Back', actividades_path %>
</div>

app/views/actividades/show.html.erb
<div class="container" style="margin-top: 100px">

  <%=	 @actividad.name %>

</div>